### ISSUE TITLE
华为P8移动版，5.0系统，java.lang.IllegalStateException

### ISSUE THREAD

**Issue by huangshengsen** [pili-engineering/PLDroidMediaStreaming#168]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
	at com.pili.pldroid.streaming.av.encoder.c.a(Unknown Source)
	at com.pili.pldroid.streaming.av.a.a(Unknown Source)
	at com.pili.pldroid.streaming.av.video.b.b(Unknown Source)
	at com.pili.pldroid.streaming.av.video.b$a.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at com.pili.pldroid.streaming.av.video.b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:831)

**Comment by jpxiong** [comment]
已修复，预计下周会更新版本。

**Comment by jpxiong** [comment]
请升级到最新版本。
