### ISSUE TITLE
有时候会报这种错误，这是什么原因导致的呐。

### ISSUE THREAD

**Issue by jugg0109** [pili-engineering/PLDroidMediaStreaming#193]
java.lang.NullPointerException
Attempt to invoke interface method 'void com.qiniu.pili.droid.streaming.microphone.a$a.a(java.nio.ByteBuffer, int, long, boolean)' on a null object reference

**Comment by jpxiong** [comment]
版本号是多少，具体行号帮忙提供下吧

**Comment by huazidev** [comment]
同样的问题，版本v2.0.3，是在音频直播录制端，调mMediaStreamingManager.pause();会出现此问题
mMediaStreamingManager初始化为：
mMediaStreamingManager = new MediaStreamingManager(this, AVCodecType.HW_AUDIO_CODEC); 
        mMediaStreamingManager.prepare(mProfile);
        mMediaStreamingManager.setStreamingStateListener(this);

具体的错误：
E/AndroidRuntime: FATAL EXCEPTION: MicrophoneCapture
                                                                       Process: im.mixbox.magnet.beta, PID: 13172
                                                                       java.lang.NullPointerException: Attempt to invoke interface method 'void com.qiniu.pili.droid.streaming.microphone.a$a.a(java.nio.ByteBuffer, int, long, boolean)' on a null object reference
                                                                           at com.qiniu.pili.droid.streaming.microphone.a.b(AudioManager.java:214)
                                                                           at com.qiniu.pili.droid.streaming.microphone.a.run(AudioManager.java:163)
                                                                           at java.lang.Thread.run(Thread.java:818)
10
