### ISSUE TITLE
切换网络时导致crash

### ISSUE THREAD

**Issue by KevinSgun** [pili-engineering/PLDroidMediaStreaming#228]
切换网络时导致crash（由wifi状态切换至	4G网络）
03-13 12:45:08.201 31582-31979/com.godo.maixiang E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                   Process: com.godo.maixiang, PID: 31582
                                                                   java.lang.ClassCastException: android.telephony.CellInfoCdma cannot be cast to android.telephony.CellInfoLte
                                                                       at com.pili.pldroid.player.report.common.a.i(Util.java:814)
                                                                       at com.pili.pldroid.player.report.core.f.i(QosStatusRecorder.java:89)
                                                                       at com.pili.pldroid.player.report.core.f.j(QosStatusRecorder.java:111)
                                                                       at com.pili.pldroid.player.report.core.f.d(QosStatusRecorder.java:67)
                                                                       at com.pili.pldroid.player.report.core.d$2$1.run(QosReceiver.java:52)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)

**Comment by Jhuster** [comment]
@KevinSgun 这个问题时 PLDroidPlayer  播放器 1.5.0 版本在某些双卡机型上的问题，建议先切回上一个版本的播放器，我们近期给出播放器修复版本
