### ISSUE TITLE
GLSurfaceView空指针异常。。

### ISSUE THREAD

**Issue by zZiv** [pili-engineering/PLDroidMediaStreaming#232]
Process: com.laibu.zhibo, PID: 7063
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.surfaceCreated()' on a null object reference
                                                                   at android.opengl.GLSurfaceView.surfaceCreated(GLSurfaceView.java:556)
                                                                   at android.view.SurfaceView.updateWindow(SurfaceView.java:675)
                                                                   at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
                                                                   at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2404)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1326)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6694)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                   at android.os.Looper.loop(Looper.java:199)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5775)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by MuseYkh** [comment]
请问后来是怎么解决的

**Comment by ConanHolmes** [comment]
我也遇到这个问题...请问解决了吗？

**Comment by wuxiaojun123** [comment]
我也遇到这个问题了，请问解决了吗

**Comment by liamyu** [comment]
为了方便碰到同样问题的小伙伴，我说一下我遇到这个问题的情形及解决方法。

主播开始直播时请求麦克风和相机权限，这时候如果CameraPreviewFrameView是定义在xml里的，那么就会因为没有及时初始化setRenderer导致上面的NPE，所以我的解决方法是，确保有权限以后才把CameraPreviewFrameView加到布局里。
