### ISSUE TITLE
弱网环境下，音频推流引起崩溃的bug

### ISSUE THREAD

**Issue by huazidev** [pili-engineering/PLDroidMediaStreaming#233]
在联通2G的弱网环境下，音频推流，尝试推流很久之后会走到：AUDIO_RECORDING_FAIL，即音频录制失败状态，就算没有走到这个状态，一段时间后，如果此时关闭页面，调mMediaStreamingManager.destroy()方法会引起崩溃，报空指针错误。
出现这种情况时，会一直打下面两个log(不是同时出现)：
Log.e("PLAudioManager", "callback listener is null !!!");
Log.w("PLAudioManager", "AudioRecord read audioDataLength: 0");

推流sdk：2.1.3
测试机: 小米note
OS:  android 6.0 , miui 8.1

**Comment by HugoLipeng** [comment]
这里面
public boolean onRecordAudioFailedHandled(int code) {
            return false;
        }
需要直接返回 FALSE 处理

**Comment by huazidev** [comment]
返回false，没有效果，还是会有崩溃发生
```
05-04 10:33:58.970 17713-2991/im.mixbox.magnet.beta E/AndroidRuntime: FATAL EXCEPTION: MicrophoneCapture
                                                                      Process: im.mixbox.magnet.beta, PID: 17713
                                                                      java.lang.NullPointerException: Attempt to invoke interface method 'void com.qiniu.pili.droid.streaming.microphone.a$a.a(java.nio.ByteBuffer, int, long, boolean)' on a null object reference
                                                                          at com.qiniu.pili.droid.streaming.microphone.a.b(AudioManager.java:223)
                                                                          at com.qiniu.pili.droid.streaming.microphone.a.run(AudioManager.java:159)
                                                                          at java.lang.Thread.run(Thread.java:818)

```

**Comment by geeklok** [comment]
@huazidev 可以的话请附上从推流开始的完整 log
