### ISSUE TITLE
版本升级之后  ，JNI层  一直播就报错  ？

### ISSUE THREAD

**Issue by sight-wxc** [pili-engineering/PLDroidMediaStreaming#239]
本来是以前老版本，更新版本之后碰到 初始化直播后 就奔溃：
抓取到的奔溃信息：
-08 15:44:38.606 18040-18040/com.qianhai.yumeiren E/BasePresenter_log: 直播 开始 房间id:live259283130
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception 'java.lang.NoSuchMethodError' thrown in java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String):-2
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]     in call to GetMethodID
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65] "Thread-12322" prio=5 tid=68 Runnable
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x136b4ca0 self=0x9c131c00
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   | sysTid=19005 nice=0 cgrp=default sched=0/0 handle=0xa01a0c00
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=0 stm=0 core=2 HZ=100
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   | stack=0x93bf2000-0x93bf4000 stackSize=1036KB
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #00 pc 00004e04  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #01 pc 00003631  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #02 pc 00251401  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+68)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #03 pc 00234d27  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+146)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #04 pc 000b3c2f  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+582)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #05 pc 000b435f  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+58)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #06 pc 000b7425  /system/lib/libart.so (_ZN3art11ScopedCheckC2EP7_JNIEnviPKc+1284)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #07 pc 000b95b3  /system/lib/libart.so (_ZN3art8CheckJNI11GetMethodIDEP7_JNIEnvP7_jclassPKcS6_+26)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #08 pc 0000fbbd  /data/app/com.qianhai.yumeiren-2/lib/arm/libpldroid_streaming_h264_encoder.so (JNI_OnLoad+100)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #09 pc 001dd5f1  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_6HandleINS_6mirror11ClassLoaderEEEPS7_+1572)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #10 pc 00204621  /system/lib/libart.so (_ZN3artL18Runtime_nativeLoadEP7_JNIEnvP7_jclassP8_jstringP8_jobjectS5_+496)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   native: #11 pc 0001a45d  /system/framework/arm/boot.oat (Java_java_lang_Runtime_nativeLoad__Ljava_lang_String_2Ljava_lang_ClassLoader_2Ljava_lang_String_2+152)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at java.lang.Runtime.nativeLoad(Native method)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at java.lang.Runtime.doLoad(Runtime.java:429)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   - locked <0x2f341895> (a java.lang.Runtime)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at java.lang.Runtime.loadLibrary(Runtime.java:370)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at java.lang.System.loadLibrary(System.java:988)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.SharedLibraryNameHelper.a(SharedLibraryNameHelper.java:208)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.SharedLibraryNameHelper.c(SharedLibraryNameHelper.java:189)
06-08 15:44:38.681 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.av.encoder.PLH264Encoder.<clinit>(PLH264Encoder.java:19)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.SharedLibraryNameHelper.a(SharedLibraryNameHelper.java:155)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.c.ag(MediaStreamingManager.java:1707)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.c.af(MediaStreamingManager.java:1700)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qiniu.pili.droid.streaming.c.f(MediaStreamingManager.java:599)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at com.qianhai.yumeiren.mvp.view.activity.live.LivePushActivity$1.run(LivePushActivity.java:167)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)
06-08 15:44:38.686 18040-19005/com.qianhai.yumeiren A/art: sart/runtime/check_jni.cc:65] 
06-08 15:44:38.956 18040-18040/com.qianhai.yumeiren E/ViewRootImpl: sendUserActionEvent() mView == null

其中的 /libpldroid_streaming_h264_encoder.so  这个库里报错？  替换成库里新的so库也不行

**Comment by sight-wxc** [comment]
可能是本人stduio出了问题~更新之后 就没问题了~
