### ISSUE TITLE
只使用StreamingManager做音频推流，只用来推流prepare的时候报Only support 16:9/4:3 ratio!错误

### ISSUE THREAD

**Issue by ityancs** [pili-engineering/PLDroidMediaStreaming#246]
Caused by: java.lang.IllegalArgumentException: Only support 16:9/4:3 ratio!
at com.qiniu.pili.droid.streaming.StreamingProfile.getVideoEncodingSize(StreamingProfile.java:1221)
at com.qiniu.pili.droid.streaming.StreamingManager.t(StreamingManager.java:592)
at com.qiniu.pili.droid.streaming.StreamingManager.prepare(StreamingManager.java:157)

只用来推音频流，不使用音频和视频的采集，prepare的时候报Only support 16:9/4:3 ratio!错误

**Comment by ityancs** [comment]
问题解决了
mProfile.setPreferredVideoEncodingSize(0, 0, 320, 240)
不过我只用到音频的推流不涉及视频，不知道为嘛还要设置这个属性

如果不设置会走下面逻辑
public StreamingProfile.VideoEncodingSize getVideoEncodingSize(PREVIEW_SIZE_RATIO var1) {
        if(this.b != null) {
            return this.b;
        } else if(var1 == PREVIEW_SIZE_RATIO.RATIO_16_9) {
            return this.a(E, this.a);
        } else if(var1 == PREVIEW_SIZE_RATIO.RATIO_4_3) {
            return this.a(F, this.a);
        } else {
            throw new IllegalArgumentException("Only support 16:9/4:3 ratio!");
        }
    }

先不关问题，想知道这里是必须的吗?
