### ISSUE TITLE
setSurfaceTextureCallback中onSurfaceChanged方法glerror

### ISSUE THREAD

**Issue by Lei13** [pili-engineering/PLDroidMediaStreaming#254]
使用的 pldroid-media-streaming-2.0.4.jar 在华为mate8 EMU5.0  android 7.0 上 发起直播偶尔会崩溃，glError 0x502,不知道具体原因，在很多地方加上GLE.checkError ,发现在onSurfaceChanged回调中一开始就崩溃了；可以麻烦帮忙看看吗？谢谢~

`FATAL EXCEPTION: GLThread 1469
Process: com.thinksns.zhibo.android, PID: 12504
java.lang.RuntimeException: 'updateSurfaceSize...start: glError 0x502
at com.jess.camerafilters.util.GlUtil.checkGlError(GlUtil.java:129)
at com.jess.camerafilters.base.FilterManager.updateSurfaceSize(FilterManager.java:53)
at com.zhiyicx.zhibolibrary.presenter.PublishPresenter$6.onSurfaceChanged(PublishPresenter.java:294)
at com.zhiyicx.zhibosdk.manage.ZBStreamingClient$5.onSurfaceChanged(ZBStreamingClient.java:617)
at com.qiniu.pili.droid.streaming.cam.d.onSurfaceChanged(CameraSurfaceRenderer.java:272)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1564)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1267)`

**Comment by Lei13** [comment]
已解决，更新SDK V2.2.2
