### ISSUE TITLE
连续开启新直播，大概率出现直播没有声音

### ISSUE THREAD

**Issue by DingZheng2017** [pili-engineering/PLDroidMediaStreaming#280]
01-23 16:03:26.311 4290-6119/edu.www.qsjs W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff3
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2615)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.encoder.c.a(PLHWEncoder.java:241)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.a.a(EncoderCore.java:82)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.muxer.c.a(PLMuxer.java:344)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.muxer.d.a(PLVideoMuxer.java:176)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.encoder.c.a(PLHWEncoder.java:212)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.a.a(EncoderCore.java:72)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.audio.d.a(MicrophoneTransfer.java:52)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.av.audio.d.a(MicrophoneTransfer.java:43)
01-23 16:03:26.312 4290-6119/edu.www.qsjs W/System.err:     at com.qiniu.pili.droid.streaming.StreamingManager.inputAudioFrame(StreamingManager.java:384)

**Comment by DingZheng2017** [comment]
vivo x9，Android 7.1.1；推流使用inputStreamManager；在测试权限的时候极易出现改问题：
1 在系统设置里--》权限--》指定应用--》声音--》总是允许
2推流前先进行权限判断，赋予权限
3推流（出现如上问题）
