### ISSUE TITLE
进入推流页面，刚READY之后就报错这个，请问是什么导致的？

### ISSUE THREAD

**Issue by senonwx** [pili-engineering/PLDroidMediaStreaming#298]
I/PLDroidMediaStreaming: Pili-Encode:VideoEncoderCore:found codec: OMX.MTK.VIDEO.ENCODER.AVC
I/PLDroidMediaStreaming: Pili-Encode:VideoEncoderCore:found colorFormat:[19,808596553]
I/PLDroidMediaStreaming: Pili-Encode:VideoEncoderCore:encoding rotation:270
I/PLDroidMediaStreaming: Pili-Encode:VideoEncoderCore:w:0, h:0,iFrameInterval:0,fps:0,bitrate:0
E/AndroidRuntime: FATAL EXCEPTION: YUVDataTransfer
                  Process: com.senon.liveqndemo, PID: 15111
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.qiniu.pili.droid.streaming.StreamingProfile$H264Profile.ordinal()' on a null object reference
                      at com.qiniu.pili.droid.streaming.av.video.e.a(VideoEncoderCore.java:65)
                      at com.qiniu.pili.droid.streaming.av.video.e.<init>(VideoEncoderCore.java:129)
                      at com.qiniu.pili.droid.streaming.av.video.g.a(YUVDataTransfer.java:198)
                      at com.qiniu.pili.droid.streaming.av.video.g.a(YUVDataTransfer.java:20)
                      at com.qiniu.pili.droid.streaming.av.video.g$a.handleMessage(YUVDataTransfer.java:274)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.os.HandlerThread.run(HandlerThread.java:61)
E/memtrack_graphic: graphic_memtrack_get_memory error to open /sys/kernel/debug/ion/clients/15111: Permission denied

**Comment by senonwx** [comment]
已解决 
缺少配置：
        //Video quality config
        encodingConfig.mIsVideoQualityPreset = true;

        //Video size config
        encodingConfig.mIsVideoSizePreset = true;
