### ISSUE TITLE
引用happy-dns，还报NoSuchMethodError错误

### ISSUE THREAD

**Issue by muxiaolin** [pili-engineering/PLDroidMediaStreaming#321]
为什么引用的dns库还报com/qiniu/android/dns/IResolver，NoSuchMethodError错误？

dependencies  依赖了  implementation 'com.qiniu:happy-dns:0.2.16'

/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qiniu.pili.droid.streaming.demo, PID: 14126
    java.lang.NoSuchMethodError: No static method defaultResolver()Lcom/qiniu/android/dns/IResolver; in class Lcom/qiniu/android/dns/local/AndroidDnsServer; or its super classes (declaration of 'com.qiniu.android.dns.local.AndroidDnsServer' appears in /data/app/com.qiniu.pili.droid.streaming.demo-8yI_WMZNjOmePcz4Ggd2Tw==/base.apk)
        at a.a.a.a.a.e.j.c(Util.java:4)
        at com.qiniu.pili.droid.streaming.StreamingProfile.<clinit>(StreamingProfile.java:1)
        at com.qiniu.pili.droid.streaming.demo.activity.AVStreamingActivity.initEncodingProfile(AVStreamingActivity.java:232)
        at com.qiniu.pili.droid.streaming.demo.activity.AVStreamingActivity.onCreate(AVStreamingActivity.java:150)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3868)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)

**Comment by HugoLipeng** [comment]
你好，目前pull最新的demo，你那边可以复现吗？

**Comment by yingzikeji** [comment]
一直都存在，SDK3.0和happy-dns:0.2.16一起就会。换成happy-dns:0.2.8 就不会，

**Comment by BoleLiu** [comment]
如果您使用的是 v3.0.1 版本，那么需要升级到对应的 HappyDNS 版本：0.2.16
如果您使用的是 v3.0.1 之前的版本，那么继续使用 0.2.8 即可，无需升级 HappyDNS 版本
